# Generated by Django 5.1 on 2024-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
    ]
