# Generated by Django 5.1 on 2024-09-16 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('products', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='products.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5, max_length=5),
        ),
    ]
