# Generated by Django 5.1 on 2024-09-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_alter_product_managers_product_stock_orderitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
